apiVersion: v1
kind: Service
metadata:
  name: rag-service
  namespace: rag
spec:
  type: NodePort
  selector:
    app: rag-app
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30036  # optional fixed port, else Kubernetes assigns a random one
